spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: qq_route
          uri: lb://jpetstore-product
          predicates:
            - Path=/catalog/**
#          filters:
#            - RewritePath=/product/(?<segment>.*),/$\{segment}


        - id: test_route
          uri: lb://jpetstore-account
          predicates:
            - Path=/account/**
#          filters:
#            - RewritePath=/account/(?<segment>.*),/$\{segment}



#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}


  application:
    name: jpetstore-gateway


