spring:
  redis:
    database: 4
    host: localhost
    port: 6379
#    password: 123456
    lettuce:
      pool:
        max-active: 300
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  session:
    store-type: redis

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


    gateway:
      routes:
        - id: p_route
          uri: lb://jpetstore-product
          predicates:
            - Path=/catalog/**,/searchProduct/**
#          filters:
#            - RewritePath=/product/(?<segment>.*),/$\{segment}
        - id: a_route
          uri: lb://jpetstore-account
          predicates:
            - Path=/account/**
        - id: o_route
          uri: lb://jpetstore-order
          predicates:
            - Path=/cart/**,/order/**




  application:
    name: jpetstore-gateway


