spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: test_route
          uri: http://localhost:7001
          predicates:
            - Path=/account/viewLoginForm/**

        - id: qq_route
          uri: http://localhost:7002
          predicates:
            - Path=/catalog/main
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}


  application:
    name: jpetstore-gateway


